import { Roboto } from 'next/font/google'
import './globals.css'
import Navbar from '@/src/components/Navbar'

const roboto = Roboto({ subsets: ['latin'], weight: ["300", "400", "700"],style: ["italic", "normal"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar></Navbar>
        <main className="container m-auto h-[calc(100vh-4rem)] flex justify-center items-center">
          {children}
        </main>
     </body>
    </html>
  )
}
